CREATE DATABASE RouteX_DB;
GO
USE RouteX_DB;
GO

CREATE TABLE Users (
    UserId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    PasswordHash NVARCHAR(256) NOT NULL,
    Role NVARCHAR(50) NOT NULL CHECK (Role IN ('SYSTEM_ADMIN', 'INVENTORY_MANAGER', 'FLEET_DISPATCHER', 'FIELD_DRIVER')),
    Status NVARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (Status IN ('ACTIVE', 'INACTIVE', 'LOCKED')),
    FailedLoginAttempts INT NOT NULL DEFAULT 0,
    LastLoginDate DATETIME NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Warehouse (
    WarehouseId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(100) NOT NULL,
    LocationAddress NVARCHAR(255) NOT NULL,
    MaxCapacity INT NOT NULL CHECK (MaxCapacity > 0),
    IsActive BIT NOT NULL DEFAULT 1
);

CREATE TABLE InventoryItem (
    ItemId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    SKU NVARCHAR(50) UNIQUE NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Quantity INT NOT NULL CHECK (Quantity >= 0),
    ExpiryDate DATE NOT NULL,
    WarehouseId UNIQUEIDENTIFIER NOT NULL,
    ReorderThreshold INT NOT NULL CHECK (ReorderThreshold > 0),
    LastRestockDate DATETIME NOT NULL DEFAULT GETDATE(),
    IsActive BIT NOT NULL DEFAULT 1,
    CONSTRAINT FK_InventoryItem_Warehouse FOREIGN KEY (WarehouseId) REFERENCES Warehouse(WarehouseId)
);

CREATE TABLE ShipmentOrder (
    OrderId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ItemId UNIQUEIDENTIFIER NOT NULL,
    RequiredQty INT NOT NULL CHECK (RequiredQty > 0),
    DestinationAddress NVARCHAR(255) NOT NULL,
    Priority NVARCHAR(20) NOT NULL CHECK (Priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    Status NVARCHAR(30) NOT NULL DEFAULT 'PENDING_APPROVAL' CHECK (Status IN ('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'DISPATCHED')),
    ExpectedDeliveryDate DATE NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    RejectionReason NVARCHAR(255) NULL,
    CONSTRAINT FK_ShipmentOrder_InventoryItem FOREIGN KEY (ItemId) REFERENCES InventoryItem(ItemId)
);

CREATE TABLE Vehicle (
    VehicleId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    LicensePlate NVARCHAR(20) UNIQUE NOT NULL,
    Capacity INT NOT NULL CHECK (Capacity > 0),
    Status NVARCHAR(30) NOT NULL DEFAULT 'AVAILABLE' CHECK (Status IN ('AVAILABLE', 'IN_TRANSIT', 'MAINTENANCE_HOLD')),
    CurrentLocation NVARCHAR(100) NOT NULL,
    Mileage INT NOT NULL DEFAULT 0
);

CREATE TABLE Shipment (
    ShipmentId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    VehicleId UNIQUEIDENTIFIER NOT NULL,
    DriverId UNIQUEIDENTIFIER NOT NULL,
    Status NVARCHAR(30) NOT NULL DEFAULT 'DISPATCHED' CHECK (Status IN ('DISPATCHED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED')),
    AssignedAt DATETIME NOT NULL DEFAULT GETDATE(),
    CompletedAt DATETIME NULL,
    CONSTRAINT FK_Shipment_Vehicle FOREIGN KEY (VehicleId) REFERENCES Vehicle(VehicleId),
    CONSTRAINT FK_Shipment_Driver FOREIGN KEY (DriverId) REFERENCES Users(UserId)
);

CREATE TABLE Shipment_Orders_Map (
    ShipmentId UNIQUEIDENTIFIER NOT NULL,
    OrderId UNIQUEIDENTIFIER NOT NULL,
    DeliverySequence INT NOT NULL DEFAULT 1,
    PRIMARY KEY (ShipmentId, OrderId),
    CONSTRAINT FK_ShipmentOrdersMap_Shipment FOREIGN KEY (ShipmentId) REFERENCES Shipment(ShipmentId),
    CONSTRAINT FK_ShipmentOrdersMap_Order FOREIGN KEY (OrderId) REFERENCES ShipmentOrder(OrderId)
);

CREATE TABLE VehicleIssue (
    IssueId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    VehicleId UNIQUEIDENTIFIER NOT NULL,
    DriverId UNIQUEIDENTIFIER NOT NULL,
    Description NVARCHAR(500) NOT NULL,
    Category NVARCHAR(50) NOT NULL,
    GpsLocation NVARCHAR(100) NOT NULL,
    Timestamp DATETIME NOT NULL DEFAULT GETDATE(),
    IsResolved BIT NOT NULL DEFAULT 0,
    CONSTRAINT FK_VehicleIssue_Vehicle FOREIGN KEY (VehicleId) REFERENCES Vehicle(VehicleId),
    CONSTRAINT FK_VehicleIssue_Driver FOREIGN KEY (DriverId) REFERENCES Users(UserId)
);

CREATE TABLE MaintenanceRecord (
    RecordId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    IssueId UNIQUEIDENTIFIER NOT NULL,
    ResolvedDate DATETIME NOT NULL DEFAULT GETDATE(),
    ResolutionNotes NVARCHAR(500) NOT NULL,
    RepairCost DECIMAL(10,2) NULL,
    CONSTRAINT FK_MaintenanceRecord_VehicleIssue FOREIGN KEY (IssueId) REFERENCES VehicleIssue(IssueId)
);

CREATE TABLE AuditLog (
    LogId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ActorId UNIQUEIDENTIFIER NULL,
    Action NVARCHAR(100) NOT NULL,
    EntityType NVARCHAR(50) NOT NULL,
    IpAddress NVARCHAR(45) NULL,
    Timestamp DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_AuditLog_Actor FOREIGN KEY (ActorId) REFERENCES Users(UserId)
);
GO
